spring:
  application.name: shareit
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    driver-class-name: org.postgresql.Driver
    username: shareituser
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      format_sql: true
  sql:
    init:
      mode: always

