DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;

CREATE TABLE IF NOT EXISTS users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100),
                       email VARCHAR(50) UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description VARCHAR(250) NOT NULL,
                          requestor_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
                          created TIMESTAMP WITHOUT TIME ZONE DEFAULT (now())
);

CREATE TABLE IF NOT EXISTS items (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100),
                       description VARCHAR(250),
                       is_available BOOL DEFAULT FALSE,
                       owner_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
                       request_id BIGINT DEFAULT NULL REFERENCES requests (id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          start_date TIMESTAMP WITHOUT TIME ZONE,
                          end_date TIMESTAMP WITHOUT TIME ZONE,
                          item_id BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
                          booker_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
                          status VARCHAR(10) DEFAULT 'WAITING'
);

CREATE TABLE IF NOT EXISTS comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          text VARCHAR(250),
                          item_id BIGINT NOT NULL REFERENCES items (id) ON DELETE CASCADE ON UPDATE CASCADE,
                          user_id BIGINT DEFAULT NULL REFERENCES users (id) ON DELETE SET NULL ON UPDATE CASCADE,
                          created TIMESTAMP WITHOUT TIME ZONE DEFAULT (now())
);
